name: Create Unity Package

on:
  - push

jobs:
  prebuild:
    runs-on: ubuntu-latest
    outputs:
      package_name: ${{steps.package_name.outputs.package_name}}
    steps:
      - id: package_name
        run: echo "::set-output name=package_name::$(echo ${GITHUB_REPOSITORY##*/})-$(echo ${GITHUB_REF##refs/*/})"

  release:
    needs:
      - prebuild
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{runner.os}}-node_modules
      - name: Install dependencies
        run: npm install -D semantic-release @semantic-release/git @semantic-release/github @semantic-release/exec semantic-release-gitmoji

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          path: dist/

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd Packages/com.nekometer.esnya.udon-simple-cars && npx semantic-release
